### PR TITLE
Drop `spawn-sync` dependency

### PR DESCRIPTION
**Pull request by fregante**
_suspiciously easy_

- Part of https://github.com/mozilla/node-fx-runner/issues/89

### CODE REVIEW

**Review by Rob--W — APPROVED** [review]
The module is a drop-in replacement for spawnSync that has been supported for a long while now ( https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options ), hence the trivial replacement.

Thanks for your patch!

**Comment by OxiDoxi** [comment]
@Rob--W Could you please release a new version of `fx-runner` and also update the version in `web-ext`

This `spawn-sync` package you were using (not even the latest version) has a very suspicious postinstall which I don't want to run at all

https://github.com/ForbesLindesay/spawn-sync/blob/1.0.15/postinstall.js

**Comment by fregante** [comment]
There are a couple more dependency changes waiting to be merged before/after that's done:

https://github.com/mozilla/node-fx-runner/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+author%3Afregante

**Comment by Rob--W** [comment]
> @Rob--W Could you please release a new version of `fx-runner` and also update the version in `web-ext`

There are some open maintenance tasks before we are going to publish a new version.

> This `spawn-sync` package you were using (not even the latest version) has a very suspicious postinstall which I don't want to run at all
> 
> https://github.com/ForbesLindesay/spawn-sync/blob/1.0.15/postinstall.js

That postinstall hooks installs try-spawn-sync if the system does not support child_process.spawnSync. It is a no-op otherwise. All currently supported Node.js versions support this, hence its removal from 2.0.0 of the package.

**Pull request merged**
